---
- name: configuration of repo
  hosts: all
  become: true
  tasks:
  roles:
    - basic

- name: deploy haproxy to frontends
  hosts: frontends
  gather_facts: true
  become: true
  roles:
    - haproxy

- name: deploy tomcat to apps server
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - tomcat

- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  roles:
    - postgressql

- name: deploy apache
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - apache
