---
- name: configuration of repo
  hosts: 
    - frontends
    - apps
    - appdbs
  become: true
  roles:
    - basic
  tags:
    - configure_repos
    - tested

- name: deploy tomcat to apps server
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - tomcat
  tags:
    - configure_app-server
    - tested

- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  roles:
    - postgressql
  tags:
    - configure_db

# - name: deploy apache
#   hosts: webservers
#   gather_facts: false
#   become: true
#   roles:
#     - apache

- name: deploy haproxy to frontends
  hosts: frontends
  gather_facts: true
  become: true
  roles:
    - haproxy
  tags:
    - configure_haproxy
    - tested

- name: verify
  hosts: frontends
  gather_facts: false
  become: true
  tasks:
  - name: verify loadbalance web url
    tags:
      - verify
    uri:
      url: http://localhost
      status_code: 200
    retries: 5
    delay: 30
