---
#create 3tier apps testing env at OSP
- hosts: jumpbox
  gather_facts: false
  vars_files:
    - ./osp_create_3tierapps_vars.yml
  tasks:
  - name: Create a servers instance
    os_server:
      cloud: ospcloud
      name: "{{ item.name }}"
      image: "{{ item.image }}"
      meta: "group={{ item.webserver_group }},deployment_name={{ item.deployment }}"
      flavor: "{{ item.flavor }}"
      security_groups: "{{ item.security_groups }}"
      key_name: ansible_ssh
      nics:
      - net-name: int_network
      userdata: |
        #!/bin/bash
        curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
        cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
        curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
        cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
    with_items: "{{ servers }}"
  - name: Add floating IP to servers
    os_floating_ip:
      cloud: ospcloud
      state: present
      reuse: yes
      server: "{{ item.name }}"
      network: ext_network
      wait: true
      timeout: 180
    with_items: "{{ servers }}"