---
#deploy 3tier to osp environment
- hosts: jumpbox
  gather_facts: false
  tasks:
   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
     register: result
   - name: Add host to
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      timeout: 120
     with_items: "{{result.ansible_facts.openstack_servers}}"
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
      timeout: 120
     with_items: "{{result.ansible_facts.openstack_servers}}"
# - hosts: dev
#   gather_facts: false
#   become: yes
#   roles:
#     - basic

# - hosts: lbserver
#   gather_facts: false
#   become: yes
#   roles:
#     - haproxy

# - hosts: appserver
#   gather_facts: false
#   become: yes
#   roles:
#     - tomcat

# - hosts: database
#   gather_facts: false
#   become: yes
#   roles:
#     - postgressql

# - hosts: webservers
#   gather_facts: false
#   become: yes
#   roles:
#     - apache
# - include: so-configuration.yaml
# - include: fuse-installation.yaml
- include: better-playbook-3tier.yaml