---
- name: Add production bastion
  hosts: bastion
  tasks:
    - name: Add bastion host to metadata group
      #  tags: dynamic_inventory
      add_host:
        name: "bastion.{{ guid }}.example.opentlc.com"
        ansible_ssh_host: "bastion.{{ guid }}.example.opentlc.com"
        ansible_ssh_user: ec2-user
        ansible_become: "yes"
        groups: "prod-bastion"
- name: Deploy three tier to production
  hosts: prod-bastion
  become: true
  tasks:
    - name: download better playbook
      get_url:
        url: https://raw.githubusercontent.com/yohanesws/ansible-3tier-apps/master/better-playbook-3tier.yml
        dest: /root/better-playbook-3tier.yml
    - name: running ansible on prod bastion
      shell: "ansible-playbook better-playbook-3tier.yml -e 'GUID={{ guid }}'"
      args:
        chdir: /root
        executable: /bin/bash
      register: deployprod
    - debug: var=deployprod