---
- hosts: towers
  become: true
  tasks:
    - name: download private key
      get_url:
        url: http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
        dest: /var/lib/awx/.ssh/openstack.pem
        owner: awx
        group: awx
        mode: 0400