---
# tasks file for postgressql
- name: install postgres
  yum:
    name: postgresql-server
    state: latest
- name: Check if PostgreSQL database is initialized.
  stat:
    path: "/var/lib/pgsql/data/PG_VERSION"
  register: pg_dir_version
- debug:
    var: pg_dir_version.stat.exists
- name: initilize postgres
  command: postgresql-setup initdb
  when: pg_dir_version.stat.exists == False
- name: enable postgresql at boot
  service:
    name: postgresql
    enabled: yes
- name: start postgres
  service:
    name: postgresql.service
    state: started