---
# tasks file for postgressql
- name: install postgres
  yum:
    name: postgresql-server
    state: latest
  notify: "init postgres"
- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes
- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"
- name: start postgres
  service:
    name: postgresql.service
    state: started